"""Streamlit live dashboard — Predictive Maintenance.

Run with:
    streamlit run src/dashboard/app.py

Layout (top to bottom)
-----------------------
  Sidebar      — file selector, speed slider, play/pause, reset
  Status banner— full-width colour-coded alert status
  Severity grid— 4 fault columns (current + 60s forecast)
  PID strip    — 4 live sensor channels over a rolling 5-min window
  Alert log    — timestamped ML + rule-engine events
  SHAP panel   — top-5 features driving the current prediction

Loop design
-----------
Each Streamlit rerun advances exactly ONE simulated second (one row).
After rendering, the script calls st.rerun() after sleeping 1/speed
seconds — so at speed=10 we advance 10 rows per real second.
This gives smooth animation without batching.

@st.cache_resource
------------------
InferenceEngine loads the XGBoost model and builds the SHAP
TreeExplainer once per Streamlit server process (survives reruns,
survives multiple browser tabs).  Between CSV files the engine is
explicitly reset() — the cached object persists, its internal state
is flushed.
"""

from __future__ import annotations

import sys
import time
from collections import deque
from pathlib import Path

# When launched via `streamlit run src/dashboard/app.py` (or directly with
# python), the project root is NOT automatically on sys.path.  Add it so
# `from src.xxx import` works regardless of how the script is invoked.
_PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import pandas as pd
import serial.tools.list_ports
import streamlit as st

from src.dashboard.inference import DashboardState, InferenceEngine
from src.dashboard.streamer import CsvStreamer
from src.dashboard.styles import inject_global_styles
from src.dashboard.theme import (
    ACCENT_DATA,
    ACCENT_OK,
    ACCENT_WARN,
    ACCENT_ALERT,
    ACCENT_INFO,
    BG_BASE,
    BG_SURFACE,
    BG_RAISED,
    BORDER,
    BORDER_STRONG,
    TEXT_PRIMARY,
    TEXT_SECONDARY,
    TEXT_MUTED,
    FONT_DISPLAY,
    FONT_BODY,
    FONT_MONO,
    SEVERITY_OK,
    SEVERITY_CAUTION,
    severity_color,
)
from src.live.obd_source import LiveObdSource

# ── Page-level config (must be first Streamlit call) ─────────────────────────

st.set_page_config(
    page_title="Predictive Maintenance",
    page_icon=":wrench:",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Constants ─────────────────────────────────────────────────────────────────

_REPO_ROOT = Path(__file__).resolve().parents[2]
_DATA_DIR = _REPO_ROOT / "data" / "raw" / "carOBD"
# Fault-injection demo files (clean-column CSVs generated by scripts/generate_demo_data.py).
# Listed first in the selectbox so the demo files are at the top.
_DEMO_DIR = _REPO_ROOT / "data" / "demo"

# How many rows to keep for the live PID chart (~5 min at 1 Hz)
_HISTORY_LEN = 300

# The four PIDs shown in the live chart.  Two per panel to keep charts readable.
_LEFT_PIDS = ["ENGINE_RPM", "COOLANT_TEMPERATURE"]
_RIGHT_PIDS = ["LONG_TERM_FUEL_TRIM_BANK_1", "THROTTLE"]

_FAULT_DISPLAY = {
    "air_system": "Air System",
    "fuel_system": "Fuel System",
    "coolant_temp_sensor": "Coolant Sensor",
    "throttle_position_sensor": "TPS",
}


def _hex_with_alpha(hex_color: str, alpha: float) -> str:
    """Convert '#RRGGBB' + alpha 0–1 → 'rgba(r,g,b,a)'.  Plotly-safe.

    Inline CSS accepts 8-char hex (#RRGGBBAA) but Plotly's color validator
    does not — only 6-char hex, named colors, rgb(), rgba(), hsl(), hsla().
    Use this helper for any color that ends up in a Plotly property.
    """
    h = hex_color.lstrip("#")
    r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
    return f"rgba({r},{g},{b},{alpha:.3f})"


# ── Cached InferenceEngine (expensive: SHAP TreeExplainer built once) ─────────


@st.cache_resource
def _load_engine() -> InferenceEngine | None:
    """Load XGBoost + SHAP + FaultForecaster.  Returns None if models missing.

    The dashboard always runs the bundled training-baseline normalizer.
    Per-vehicle normalizers are consumed through
    InferenceEngine(normalizer_override=...) by scripts/score_recording.py
    and the FastAPI car flow — not through this UI.
    """
    try:
        return InferenceEngine()
    except FileNotFoundError:
        return None


# ── Session state bootstrap ───────────────────────────────────────────────────


def _init_session_state() -> None:
    defaults = {
        "source_type": "csv",  # "csv" | "live"
        "streamer": None,  # CsvStreamer | None  (csv mode)
        "live_source": None,  # LiveObdSource | None  (live mode)
        "playing": False,
        "pid_history": deque(maxlen=_HISTORY_LEN),
        "latest_state": None,  # DashboardState | None
        "alert_log": [],  # list[str]  — timestamped event strings
        "last_active_fault": "",  # track transitions for alert log
    }
    for key, val in defaults.items():
        if key not in st.session_state:
            st.session_state[key] = val


# ── Sidebar ───────────────────────────────────────────────────────────────────


def _render_sidebar(engine: InferenceEngine | None) -> float:
    """Render controls.  Returns the playback speed.  Handles all interactions."""
    st.sidebar.markdown(
        f'<div style="font-family:{FONT_DISPLAY};font-size:0.75rem;text-transform:uppercase;'
        f'letter-spacing:0.1em;color:{TEXT_MUTED};padding:4px 0 8px 0;">'
        f'<span style="display:inline-block;width:8px;height:8px;background:{ACCENT_DATA};'
        f'border-radius:2px;margin-right:8px;vertical-align:middle;"></span>'
        f"Session Controls</div>",
        unsafe_allow_html=True,
    )

    # ── Source selector ───────────────────────────────────────────────────────
    source_type = st.sidebar.radio(
        "Source",
        ["CSV replay", "Live vehicle"],
        index=0 if st.session_state.source_type == "csv" else 1,
        horizontal=True,
    )
    new_source_type = "csv" if source_type == "CSV replay" else "live"

    # Stop live source if user switched away from live mode
    if new_source_type != st.session_state.source_type:
        if st.session_state.live_source is not None:
            st.session_state.live_source.stop()
            st.session_state.live_source = None
        st.session_state.playing = False
        st.session_state.source_type = new_source_type

    st.sidebar.divider()

    speed = 1.0  # default; overridden in CSV section below

    # ── CSV mode controls ─────────────────────────────────────────────────────
    if new_source_type == "csv":
        if not _DATA_DIR.exists():
            st.sidebar.error(f"Data directory not found:\n{_DATA_DIR}")
            return 1.0

        # Demo fault files (data/demo/) listed first — they're pre-injected
        # so you see fault detection immediately.  Raw carOBD files follow.
        demo_files = sorted(_DEMO_DIR.glob("*.csv")) if _DEMO_DIR.exists() else []
        raw_files = sorted(_DATA_DIR.glob("*.csv")) if _DATA_DIR.exists() else []
        csv_files = demo_files + raw_files
        if not csv_files:
            st.sidebar.warning("No CSV files found. Run scripts/generate_demo_data.py first.")
            return 1.0

        file_labels = (
            [f"[DEMO] {p.name}" for p in demo_files]
            + [p.name for p in raw_files]
        )
        file_paths = demo_files + raw_files

        selected_label = st.sidebar.selectbox("Session file", file_labels)
        selected_idx = file_labels.index(selected_label)
        selected_path = file_paths[selected_idx]
        speed = float(
            st.sidebar.slider(
                "Playback speed (×real-time)",
                min_value=1,
                max_value=50,
                value=10,
                step=1,
            )
        )

        c1, c2 = st.sidebar.columns(2)
        play_label = "Play" if not st.session_state.playing else "Pause"
        play_clicked = c1.button(play_label, use_container_width=True)
        reset_clicked = c2.button("Reset", use_container_width=True)

        if play_clicked:
            current = st.session_state.streamer
            if current is None or current.session_id != selected_path.stem:
                if engine is not None:
                    engine.reset()
                st.session_state.streamer = CsvStreamer(selected_path, speed=speed)
                _clear_session_display()
            st.session_state.playing = not st.session_state.playing

        if reset_clicked:
            if engine is not None:
                engine.reset()
            if st.session_state.streamer is not None:
                st.session_state.streamer.reset()
            _clear_session_display()
            st.session_state.playing = False

        streamer = st.session_state.streamer
        if streamer is not None:
            st.sidebar.progress(streamer.elapsed_s / max(1, streamer.total))
            st.sidebar.caption(
                f"{streamer.elapsed_s} s / {streamer.total} s "
                f"| {streamer.remaining} s remaining"
            )

    # ── Live vehicle controls ─────────────────────────────────────────────────
    else:
        ports = [p.device for p in serial.tools.list_ports.comports()]
        if not ports:
            ports = ["(no ports found)"]
        selected_port = st.sidebar.selectbox("COM port", ports)

        live_src = st.session_state.live_source
        is_connected = live_src is not None and live_src.connected

        c1, c2 = st.sidebar.columns(2)
        connect_clicked = c1.button(
            "Disconnect" if is_connected else "Connect",
            use_container_width=True,
        )
        reset_clicked = c2.button("Reset", use_container_width=True)

        if connect_clicked:
            if is_connected:
                # Disconnect
                live_src.stop()
                st.session_state.live_source = None
                st.session_state.playing = False
            else:
                # Connect
                with st.sidebar.status("Connecting to ELM327…", expanded=False):
                    new_src = LiveObdSource(
                        port=selected_port
                        if selected_port != "(no ports found)"
                        else None,
                        sample_hz=1.0,
                    )
                    ok = new_src.connect()
                if ok:
                    new_src.start()
                    st.session_state.live_source = new_src
                    if engine is not None:
                        engine.reset()
                    _clear_session_display()
                    st.session_state.playing = True
                else:
                    st.sidebar.error(
                        "Could not connect.  Check adapter, port, and ignition."
                    )

        if reset_clicked:
            if engine is not None:
                engine.reset()
            if live_src is not None:
                live_src.reset()
            _clear_session_display()
            st.session_state.playing = False

        # Live status indicator + adapter throughput card
        live_src = st.session_state.live_source
        if live_src is not None and live_src.connected:
            hz = live_src.measured_poll_hz
            # Grade adapter throughput:
            #   >= 0.8 Hz  good — close to 1 Hz training rate
            #   0.4–0.8    degraded — features will be noisier
            #   < 0.4 Hz   poor — window feature math is unreliable
            if hz >= 0.8:
                hz_color, hz_grade = ACCENT_OK, "GOOD"
            elif hz >= 0.4:
                hz_color, hz_grade = ACCENT_WARN, "DEGRADED"
            else:
                hz_color, hz_grade = ACCENT_ALERT, "POOR"
            st.sidebar.markdown(
                f'<div style="background:{BG_RAISED};border:1px solid {BORDER};'
                f'border-radius:6px;padding:8px 12px;margin:8px 0;">'
                f'<div style="font-family:{FONT_DISPLAY};font-size:9px;'
                f'text-transform:uppercase;letter-spacing:0.1em;color:{TEXT_MUTED};">'
                f'ADAPTER THROUGHPUT</div>'
                f'<div style="display:flex;align-items:baseline;gap:8px;">'
                f'<span style="font-family:{FONT_MONO};font-size:18px;color:{TEXT_PRIMARY};">'
                f'{hz:.2f} Hz</span>'
                f'<span style="font-family:{FONT_DISPLAY};font-size:10px;'
                f'color:{hz_color};letter-spacing:0.08em;">{hz_grade}</span>'
                f'</div>'
                f'<div style="font-family:{FONT_BODY};font-size:10px;'
                f'color:{TEXT_SECONDARY};margin-top:2px;">'
                f'{len(live_src.supported_pids)}/14 PIDs supported</div>'
                f'</div>',
                unsafe_allow_html=True,
            )
            st.sidebar.caption(f"{live_src.elapsed_s} s elapsed")
        elif live_src is not None:
            st.sidebar.warning("Adapter found, waiting for ECU…")
        else:
            st.sidebar.info("Not connected.  Press Connect to start.")

    return speed


# ── Panel renderers ───────────────────────────────────────────────────────────


def _section_header(title: str) -> None:
    """Render a thin section label in Saira Condensed with a left accent bar."""
    st.markdown(
        f'<div style="display:flex;align-items:center;gap:10px;'
        f'margin:20px 0 10px 0;">'
        f'<div style="width:3px;height:16px;background:{ACCENT_DATA};'
        f'border-radius:2px;flex-shrink:0;"></div>'
        f'<span style="font-family:{FONT_DISPLAY};font-size:11px;'
        f'text-transform:uppercase;letter-spacing:0.1em;color:{TEXT_SECONDARY};">'
        f"{title}</span>"
        f"</div>",
        unsafe_allow_html=True,
    )


# Iconographic glyph inside the LED square — readable without color perception
_STATE_GLYPH: dict[str, str] = {
    ACCENT_OK:    "OK",
    ACCENT_WARN:  "!",
    ACCENT_ALERT: "X",
    ACCENT_INFO:  "~",
}


def _render_status_banner(state: DashboardState) -> None:
    """Full-width 4-lane instrument-cluster status banner.

    Lanes: [LED square] [Title / subtitle] [3 stat blocks] [Elapsed / regime]
    A 3px accent strip runs across the top edge — the dominant visual cue for
    the current machine state without relying on text alone.
    """
    alert = state.stable_alert

    # ── Determine state category ────────────────────────────────────────────
    # Data quality failure takes precedence — don't display a diagnosis on garbage data
    if not state.data_quality_ok:
        viols = state.data_quality_violations
        accent = ACCENT_ALERT
        title = "SENSOR DATA INVALID"
        subtitle_txt = "; ".join(viols[:2])
        if len(viols) > 2:
            subtitle_txt += f"  (+{len(viols) - 2} more)"
        stat1_lbl, stat1_val = "VIOLATIONS", str(len(viols))
        stat2_lbl, stat2_val = "STATUS", "HELD"
        stat3_lbl, stat3_val = "REGIME", "—"

        def _stat(label: str, value: str) -> str:
            return (
                f'<div style="display:flex;flex-direction:column;gap:2px;">'
                f'<span style="font-family:{FONT_DISPLAY};font-size:9px;text-transform:uppercase;'
                f'letter-spacing:0.12em;color:{TEXT_MUTED};">{label}</span>'
                f'<span style="font-family:{FONT_MONO};font-size:18px;font-weight:700;'
                f'color:{TEXT_PRIMARY};line-height:1;">{value}</span>'
                f"</div>"
            )

        elapsed_html = (
            f'<div style="text-align:right;min-width:96px;">'
            f'<div style="font-family:{FONT_DISPLAY};font-size:9px;text-transform:uppercase;'
            f'letter-spacing:0.12em;color:{TEXT_MUTED};">SESSION TIME</div>'
            f'<div style="font-family:{FONT_MONO};font-size:26px;font-weight:700;'
            f'color:{TEXT_PRIMARY};line-height:1.1;">{state.elapsed_s:04d} s</div>'
            f"</div>"
        )
        dq_banner = f"""
<div style="
    background-color:{BG_SURFACE};border:1px solid {BORDER};
    border-radius:8px;overflow:hidden;margin-bottom:16px;">
  <div style="height:3px;background:{accent};box-shadow:0 0 20px {accent}60;"></div>
  <div style="display:grid;grid-template-columns:52px 1fr auto auto;
              align-items:center;gap:20px;padding:16px 20px;">
    <div style="width:40px;height:40px;background:{accent};border-radius:6px;
                box-shadow:0 0 24px {accent}40;flex-shrink:0;
                display:flex;align-items:center;justify-content:center;
                font-family:{FONT_MONO};color:white;font-size:14px;font-weight:700;">
      {_STATE_GLYPH.get(accent, '?')}</div>
    <div>
      <div style="font-family:{FONT_DISPLAY};font-size:20px;font-weight:700;
                  text-transform:uppercase;letter-spacing:0.05em;
                  color:{accent};">{title}</div>
      <div style="font-family:{FONT_BODY};font-size:12px;color:{TEXT_SECONDARY};
                  margin-top:3px;">{subtitle_txt}</div>
    </div>
    <div style="display:flex;gap:28px;">
      {_stat(stat1_lbl, stat1_val)}
      {_stat(stat2_lbl, stat2_val)}
      {_stat(stat3_lbl, stat3_val)}
    </div>
    {elapsed_html}
  </div>
</div>"""
        # Collapse blank lines — CommonMark ends an HTML block at any blank line,
        # which would cause the remainder to render as literal text.
        dq_banner = "".join(line for line in dq_banner.splitlines() if line.strip())
        st.markdown(dq_banner, unsafe_allow_html=True)
        return

    if not state.buffer_ready:
        accent = ACCENT_INFO
        title = "WARMING UP"
        subtitle = "Collecting first 60 seconds of sensor data…"
        stat1_lbl, stat1_val = "ELAPSED", f"{state.elapsed_s} s"
        stat2_lbl, stat2_val = "TARGET", "60 s"
        stat3_lbl, stat3_val = "REGIME", "—"
    elif alert.active:
        from src.diagnostics.dtc_map import get_dtc
        dtc = get_dtc(alert.fault_type)
        accent = ACCENT_ALERT
        title = f"{dtc['code']} — {dtc['name'].upper()}"
        subtitle = f"{alert.windows_voted} windows confirmed · majority vote passed"
        stat1_lbl, stat1_val = "MODEL AGMT", f"{alert.confidence:.0%}"
        stat2_lbl, stat2_val = "WINDOWS", f"{alert.windows_voted}/3"
        # Pull current severity for the active fault if available
        sev = state.severities.get(alert.fault_type, 0.0)
        fcast = state.forecasts.get(alert.fault_type, 0.0)
        delta_sym = "▲" if fcast > sev + 0.02 else ("▼" if fcast < sev - 0.02 else "—")
        stat3_lbl, stat3_val = "SEVERITY", f"{sev:.0%} {delta_sym}"
    elif state.classifier_label == "cold_start":
        accent = ACCENT_WARN
        title = "COLD START"
        subtitle = "Monitoring engine warm-up arc · rules active"
        coolant = state.latest_row.get("COOLANT_TEMPERATURE", 0.0)
        stat1_lbl, stat1_val = "COOLANT", f"{coolant:.0f} °C"
        stat2_lbl, stat2_val = "TARGET", "75 °C"
        stat3_lbl, stat3_val = "ELAPSED", f"{state.elapsed_s} s"
    elif state.classifier_label in ("healthy", "warming_up"):
        accent = ACCENT_OK
        title = "ALL SYSTEMS NOMINAL"
        subtitle = f"Classifier · {state.classifier_confidence:.0%} confidence"
        stat1_lbl, stat1_val = "LABEL", "HEALTHY"
        stat2_lbl, stat2_val = "CONF", f"{state.classifier_confidence:.0%}"
        stat3_lbl, stat3_val = "ELAPSED", f"{state.elapsed_s} s"
    elif state.label_untested:
        accent = ACCENT_INFO
        label_d = state.classifier_label.replace("_", " ").upper()
        title = f"UNTESTED — {label_d}"
        subtitle = "Required PID unavailable on this vehicle · score suppressed"
        stat1_lbl, stat1_val = "STATUS", "UNTESTED"
        stat2_lbl, stat2_val = "CONF", f"{state.classifier_confidence:.0%}"
        stat3_lbl, stat3_val = "ELAPSED", f"{state.elapsed_s} s"
    else:
        # Fault suspected but voting not complete
        accent = ACCENT_WARN
        label_d = state.classifier_label.replace("_", " ").upper()
        title = f"SUSPECTED — {label_d}"
        subtitle = "Awaiting majority vote confirmation…"
        stat1_lbl, stat1_val = "CONF", f"{state.classifier_confidence:.0%}"
        stat2_lbl, stat2_val = "ELAPSED", f"{state.elapsed_s} s"
        stat3_lbl, stat3_val = "STATUS", "UNCONFIRMED"

    # ── Stat block HTML builder ──────────────────────────────────────────────
    def _stat(label: str, value: str) -> str:
        return (
            f'<div style="display:flex;flex-direction:column;gap:2px;">'
            f'<span style="font-family:{FONT_DISPLAY};font-size:9px;text-transform:uppercase;'
            f'letter-spacing:0.12em;color:{TEXT_MUTED};">{label}</span>'
            f'<span style="font-family:{FONT_MONO};font-size:18px;font-weight:700;'
            f'color:{TEXT_PRIMARY};line-height:1;">{value}</span>'
            f"</div>"
        )

    # ── Elapsed lane (right) ─────────────────────────────────────────────────
    elapsed_html = (
        f'<div style="text-align:right;min-width:96px;">'
        f'<div style="font-family:{FONT_DISPLAY};font-size:9px;text-transform:uppercase;'
        f'letter-spacing:0.12em;color:{TEXT_MUTED};">SESSION TIME</div>'
        f'<div style="font-family:{FONT_MONO};font-size:26px;font-weight:700;'
        f'color:{TEXT_PRIMARY};line-height:1.1;">{state.elapsed_s:04d} s</div>'
        f"</div>"
    )

    # ── Assemble banner ──────────────────────────────────────────────────────
    banner_html = f"""
<div style="
    background-color:{BG_SURFACE};
    border:1px solid {BORDER};
    border-radius:8px;
    overflow:hidden;
    margin-bottom:16px;
    box-shadow:0 2px 12px {BG_BASE}80;
">
  <!-- Accent strip across the top -->
  <div style="height:3px;background:{accent};
              box-shadow:0 0 20px {accent}60;"></div>

  <!-- Content grid: LED | title+sub | stats | elapsed -->
  <div style="
    display:grid;
    grid-template-columns:52px 1fr auto auto;
    align-items:center;
    gap:20px;
    padding:16px 20px;
  ">
    <!-- LED square with iconographic glyph for color-blind accessibility -->
    <div style="
      width:40px;height:40px;
      background:{accent};
      border-radius:6px;
      box-shadow:0 0 24px {accent}40;
      flex-shrink:0;
      display:flex;align-items:center;justify-content:center;
      font-family:{FONT_MONO};color:white;font-size:14px;font-weight:700;
    ">{_STATE_GLYPH.get(accent, '?')}</div>

    <!-- Title / subtitle -->
    <div>
      <div style="font-family:{FONT_DISPLAY};font-size:20px;font-weight:700;
                  text-transform:uppercase;letter-spacing:0.05em;
                  color:{TEXT_PRIMARY};line-height:1.1;">{title}</div>
      <div style="font-family:{FONT_BODY};font-size:12px;color:{TEXT_SECONDARY};
                  margin-top:4px;">{subtitle}</div>
    </div>

    <!-- 3 stat blocks -->
    <div style="display:flex;gap:28px;padding:0 8px;">
      {_stat(stat1_lbl, stat1_val)}
      {_stat(stat2_lbl, stat2_val)}
      {_stat(stat3_lbl, stat3_val)}
    </div>

    <!-- Elapsed time lane -->
    {elapsed_html}
  </div>
</div>
"""
    # Collapse blank lines — CommonMark ends an HTML block at any blank line,
    # which causes the remainder to render as literal source text rather than HTML.
    banner_html = "".join(line for line in banner_html.splitlines() if line.strip())
    st.markdown(banner_html, unsafe_allow_html=True)



def _render_pid_strip(history: deque) -> None:
    """2×2 grid of dark sparkline cards — each shows a large live value + rolling plot.

    Card layout (per PID):
      Left column  (fixed 110px): unit label, big current value, unit suffix
      Right column (flex):        axes-free plotly sparkline in ACCENT_DATA
    """
    import plotly.graph_objects as go

    _PID_META = {
        "ENGINE_RPM": ("ENGINE RPM", "", ACCENT_DATA),
        "COOLANT_TEMPERATURE": ("COOLANT", "°C", ACCENT_WARN),
        "LONG_TERM_FUEL_TRIM_BANK_1": ("LTFT", "%", ACCENT_OK),
        "THROTTLE": ("THROTTLE", "%", ACCENT_ALERT),
    }
    _PID_ORDER = list(_PID_META.keys())

    if not history:
        # Placeholder cards with no data yet
        cols = st.columns(2)
        for i, pid in enumerate(_PID_ORDER):
            label, unit, _ = _PID_META[pid]
            with cols[i % 2]:
                st.markdown(
                    f'<div class="panel-card" style="height:96px;display:flex;'
                    f'align-items:center;justify-content:center;">'
                    f'<span style="font-family:{FONT_MONO};color:{TEXT_MUTED};font-size:12px;">'
                    f"{label} — press Play</span></div>",
                    unsafe_allow_html=True,
                )
        return

    hist_df = pd.DataFrame(list(history))
    cols = st.columns(2)

    for i, pid in enumerate(_PID_ORDER):
        label, unit, line_color = _PID_META[pid]
        if pid not in hist_df.columns:
            continue

        series = hist_df[pid].dropna()
        current_val = series.iloc[-1] if len(series) else 0.0

        # Format current value: integers for RPM, 1 decimal for others
        if pid == "ENGINE_RPM":
            val_str = f"{int(current_val):,}"
        else:
            val_str = f"{current_val:.1f}"
        # Hover number format mirrors the displayed value (RPM integer, else 1dp).
        val_fmt = ",.0f" if pid == "ENGINE_RPM" else ".1f"

        # Sparkline — no axes, no labels, just the signal shape
        fig = go.Figure(
            go.Scatter(
                y=series.values,
                mode="lines",
                line={"color": line_color, "width": 1.8},
                fill="tozeroy",
                fillcolor=_hex_with_alpha(line_color, 0.094),
                hovertemplate=f"{label}: %{{y:{val_fmt}}} {unit}<extra></extra>",
            )
        )
        fig.update_xaxes(visible=False, showgrid=False)
        fig.update_yaxes(visible=False, showgrid=False)
        fig.update_layout(
            paper_bgcolor=BG_SURFACE,
            plot_bgcolor=BG_SURFACE,
            margin={"l": 0, "r": 0, "t": 0, "b": 0},
            showlegend=False,
            height=80,
        )

        with cols[i % 2]:
            # One bordered card per PID, with two columns *inside* the card:
            # value/label on the left, sparkline on the right.  Round 1's fix
            # mistakenly put a border around each sub-column, producing two
            # disconnected boxes per PID — the docstring above describes one
            # unified card containing both halves.
            with st.container(border=True):
                inner_c1, inner_c2 = st.columns([1, 3])
                with inner_c1:
                    st.markdown(
                        f'<div style="min-width:110px;padding:4px 0;">'
                        f'<div style="font-family:{FONT_DISPLAY};font-size:9px;'
                        f"text-transform:uppercase;letter-spacing:0.1em;"
                        f'color:{TEXT_MUTED};">{label}</div>'
                        f'<div style="font-family:{FONT_MONO};font-size:28px;'
                        f'font-weight:700;color:{TEXT_PRIMARY};line-height:1.1;">'
                        f"{val_str}</div>"
                        f'<div style="font-family:{FONT_BODY};font-size:10px;'
                        f'color:{TEXT_SECONDARY};">{unit}</div>'
                        f"</div>",
                        unsafe_allow_html=True,
                    )
                with inner_c2:
                    st.plotly_chart(
                        fig,
                        use_container_width=True,
                        config={"displayModeBar": False},
                    )


def _render_alert_log(log_entries: list) -> None:
    """Diagnostic terminal feed — monospace, color-coded, time-prefixed rows."""
    if not log_entries:
        st.markdown(
            f'<div class="panel-card" style="font-family:{FONT_MONO};'
            f'font-size:12px;color:{TEXT_MUTED};padding:20px 16px;">'
            f"// no alerts yet</div>",
            unsafe_allow_html=True,
        )
        return

    rows_html = ""
    for entry in reversed(log_entries[-15:]):
        # Parse entry format: "[{elapsed}s] {TYPE} — {detail}"
        # Classify entry for color coding
        if "ML ALERT" in entry:
            glyph, tag, tag_color = "▸", "ML ALERT", ACCENT_ALERT
        elif "RULE" in entry.upper():
            glyph, tag, tag_color = "⚠", "RULE", ACCENT_WARN
        elif "cleared" in entry.lower() or "healthy" in entry.lower():
            glyph, tag, tag_color = "✓", "CLEARED", ACCENT_OK
        else:
            glyph, tag, tag_color = "·", "INFO", TEXT_MUTED

        # Extract time prefix if present
        if entry.startswith("["):
            bracket_end = entry.find("]")
            time_part = entry[1:bracket_end] if bracket_end > 0 else ""
            detail = entry[bracket_end + 1 :].strip().lstrip("—").strip()
        else:
            time_part = ""
            detail = entry

        # Remove the redundant type prefix from detail (we re-render it as a tag)
        for prefix in ("ML ALERT —", "RULE —", "Alert cleared —"):
            if detail.startswith(prefix):
                detail = detail[len(prefix) :].strip()
                break

        rows_html += (
            f'<div style="display:grid;grid-template-columns:80px 20px 90px 1fr;'
            f"gap:8px;align-items:baseline;padding:8px 0;"
            f'border-bottom:1px solid {BORDER};">'
            # Time
            f'<span style="font-family:{FONT_MONO};font-size:10px;color:{TEXT_MUTED};">'
            f"[ {time_part} ]</span>"
            # Glyph
            f'<span style="font-size:12px;color:{tag_color};">{glyph}</span>'
            # Category tag
            f'<span style="font-family:{FONT_DISPLAY};font-size:9px;text-transform:uppercase;'
            f"letter-spacing:0.1em;color:{tag_color};"
            f'border:1px solid {tag_color}40;border-radius:3px;padding:1px 5px;">'
            f"{tag}</span>"
            # Detail
            f'<span style="font-family:{FONT_BODY};font-size:12px;color:{TEXT_PRIMARY};">'
            f"{detail}</span>"
            f"</div>"
        )

    st.markdown(
        f'<div class="panel-card" style="max-height:320px;overflow-y:auto;padding:8px 16px;">'
        f"{rows_html}"
        f"</div>",
        unsafe_allow_html=True,
    )


_FEATURE_NAME_MAP: dict[str, str] = {
    "LONG_TERM_FUEL_TRIM_BANK_1__mean":  "LTFT B1 avg",
    "LONG_TERM_FUEL_TRIM_BANK_1__max":   "LTFT B1 peak",
    "LONG_TERM_FUEL_TRIM_BANK_1__min":   "LTFT B1 floor",
    "LONG_TERM_FUEL_TRIM_BANK_1__delta": "LTFT B1 change",
    "LONG_TERM_FUEL_TRIM_BANK_1__std":   "LTFT B1 jitter",
    "SHORT_TERM_FUEL_TRIM_BANK_1__mean": "STFT B1 avg",
    "SHORT_TERM_FUEL_TRIM_BANK_1__std":  "STFT B1 jitter",
    "COOLANT_TEMPERATURE__mean":         "Coolant avg",
    "COOLANT_TEMPERATURE__delta":        "Coolant change",
    "INTAKE_MANIFOLD_PRESSURE__mean":    "MAP avg",
    "INTAKE_MANIFOLD_PRESSURE__max":     "MAP peak",
    "THROTTLE_TO_PEDAL_RATIO":           "TPS vs pedal",
    "MAP_PER_THROTTLE":                  "MAP / throttle",
    "FUEL_TRIM_DIVERGENCE":              "LTFT - STFT",
    "COOLANT_WARMUP_RATE":               "Warm-up rate",
    "RPM_IDLE_DRIFT":                    "Idle RPM jitter",
    "TIMING_VS_TEMP":                    "Timing deviation",
    "FUEL_LOOP_ACTIVE":                  "Closed loop",
    "THROTTLE_CMD_ACTUAL_DELTA":         "Throttle vs cmd",
    "ENGINE_RPM__mean":                  "RPM avg",
    "ENGINE_RPM__std":                   "RPM jitter",
    "THROTTLE__mean":                    "Throttle avg",
    "VEHICLE_SPEED__mean":               "Speed avg",
    "ENGINE_LOAD__mean":                 "Engine load avg",
    "TIMING_ADVANCE__mean":              "Timing advance",
    "INTAKE_AIR_TEMPERATURE__mean":      "Intake air temp",
    "CONTROL_MODULE_VOLTAGE__mean":      "Module voltage",
    # Regime one-hots — shown when regime shift is the discriminating signal
    "REGIME__COLD_START":                "Cold start regime",
    "REGIME__IDLE":                      "Idle regime",
    "REGIME__CRUISE":                    "Cruise regime",
    "REGIME__ACCEL":                     "Accel regime",
    "REGIME__DECEL":                     "Decel regime",
}


def _humanize_feature(raw_name: str) -> str:
    """Convert a raw feature column name to a workshop-readable label."""
    base = raw_name.replace("__z", "")
    if base in _FEATURE_NAME_MAP:
        return _FEATURE_NAME_MAP[base]
    return base.replace("__", " ").replace("_", " ").title()


def _render_shap_panel(state: DashboardState) -> None:
    """Dark horizontal SHAP bar chart with title strip and outside-bar labels."""
    import plotly.graph_objects as go

    if not state.top_features:
        st.markdown(
            f'<div class="panel-card" style="font-family:{FONT_MONO};'
            f'font-size:12px;color:{TEXT_MUTED};padding:20px 16px;">'
            f"// available after first 60-second window</div>",
            unsafe_allow_html=True,
        )
        return

    # Title strip — label + confidence in Saira Condensed
    label_display = state.classifier_label.replace("_", " ").upper()
    if state.label_untested:
        label_display += " (UNTESTED)"
    st.markdown(
        f'<div style="font-family:{FONT_DISPLAY};font-size:11px;'
        f"text-transform:uppercase;letter-spacing:0.1em;"
        f'color:{TEXT_SECONDARY};margin-bottom:6px;">'
        f"PREDICTING &nbsp;"
        f'<span style="color:{TEXT_PRIMARY};">{label_display}</span>'
        f"&nbsp;·&nbsp;"
        f'<span style="color:{ACCENT_DATA};font-family:{FONT_MONO};">'
        f"{state.classifier_confidence:.0%} MODEL AGREEMENT</span>"
        f"</div>",
        unsafe_allow_html=True,
    )

    names = [_humanize_feature(f[0]) for f in state.top_features]
    values = [f[1] for f in state.top_features]

    # Sort by absolute SHAP value descending, orient horizontal
    pairs = sorted(
        zip(names, values), key=lambda x: abs(x[1])
    )  # ascending for plotly (bottom-up)
    sorted_names = [p[0] for p in pairs]
    sorted_vals = [p[1] for p in pairs]

    # Color: positive → pushes toward active label (ACCENT_DATA), negative → TEXT_MUTED
    bar_colors = [ACCENT_DATA if v >= 0 else TEXT_MUTED for v in sorted_vals]

    fig = go.Figure(
        go.Bar(
            x=sorted_vals,
            y=sorted_names,
            orientation="h",
            marker={"color": bar_colors},
            text=[f"{v:+.3f}" for v in sorted_vals],
            textposition="outside",
            textfont={"family": FONT_MONO, "size": 10, "color": TEXT_SECONDARY},
            cliponaxis=False,
        )
    )
    fig.update_xaxes(visible=False, showgrid=False, zeroline=False)
    fig.update_yaxes(
        showgrid=False,
        tickfont={"family": FONT_MONO, "size": 10, "color": TEXT_SECONDARY},
    )
    fig.update_layout(
        paper_bgcolor=BG_SURFACE,
        plot_bgcolor=BG_SURFACE,
        font={"family": FONT_MONO, "color": TEXT_PRIMARY},
        margin={"l": 0, "r": 60, "t": 0, "b": 0},
        height=220,
        showlegend=False,
    )

    # st.container(border=True) provides a real wrapper that survives Streamlit's
    # render cycle — unlike st.markdown('<div>') which is auto-closed before the
    # chart renders, leaving the chart outside the card entirely.
    with st.container(border=True):
        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})


# ── Alert log helpers ─────────────────────────────────────────────────────────


def _log_append(entry: str) -> None:
    """Append to alert log only if it's not a duplicate of the last entry."""
    log = st.session_state.alert_log
    if not log or log[-1] != entry:
        log.append(entry)


def _update_alert_log(state: DashboardState) -> None:
    """Emit log entries for new rule alerts and ML alert state transitions."""
    # Rule alerts (deterministic; fire once)
    for ra in state.rule_alerts:
        entry = (
            f"[{state.elapsed_s}s] RULE — {ra.rule}: {ra.description[:80].rstrip()}…"
        )
        if entry not in st.session_state.alert_log:
            _log_append(entry)

    # ML stable alert transitions
    alert = state.stable_alert
    current_fault = alert.fault_type if alert.active else "healthy"
    if current_fault != st.session_state.last_active_fault:
        if alert.active:
            _log_append(
                f"[{state.elapsed_s}s] ML ALERT — {alert.fault_type.replace('_', ' ')} "
                f"({alert.confidence:.0%} conf, {alert.windows_voted} windows)"
            )
        elif st.session_state.last_active_fault not in ("healthy", ""):
            _log_append(f"[{state.elapsed_s}s] Alert cleared — system healthy")
        st.session_state.last_active_fault = current_fault


# ── Session display helper ────────────────────────────────────────────────────


def _clear_session_display() -> None:
    """Reset per-session display buffers without touching the source."""
    st.session_state.pid_history.clear()
    st.session_state.alert_log.clear()
    st.session_state.latest_state = None
    st.session_state.last_active_fault = ""


# ── Recommendations panel ─────────────────────────────────────────────────────


def _render_recommendations(state: DashboardState) -> None:
    """Workshop-style ordered checklist for the active fault.

    Only renders when there is a confirmed alert — positioned as the
    "what now?" call-to-action below the SHAP panel.
    """
    if not state.stable_alert.active:
        return

    from src.diagnostics.recommendations import get_steps
    from src.diagnostics.dtc_map import get_dtc

    fault = state.stable_alert.fault_type
    steps = get_steps(fault)
    if not steps:
        return
    dtc = get_dtc(fault)

    rows_html = ""
    for i, step in enumerate(steps, start=1):
        rows_html += (
            f'<div style="display:grid;grid-template-columns:24px 1fr;'
            f'gap:10px;padding:6px 0;border-bottom:1px solid {BORDER};">'
            f'<span style="font-family:{FONT_MONO};color:{ACCENT_DATA};'
            f'font-size:12px;font-weight:700;">{i:02d}</span>'
            f'<span style="font-family:{FONT_BODY};color:{TEXT_PRIMARY};'
            f'font-size:13px;line-height:1.4;">{step}</span>'
            f'</div>'
        )

    st.markdown(
        f'<div class="panel-card" style="padding:12px 16px;margin-top:12px;">'
        f'<div style="font-family:{FONT_DISPLAY};font-size:11px;'
        f'text-transform:uppercase;letter-spacing:0.1em;'
        f'color:{TEXT_SECONDARY};margin-bottom:10px;">'
        f'DIAGNOSTIC STEPS &middot; {dtc["short"].upper()}</div>'
        f'{rows_html}'
        f'</div>',
        unsafe_allow_html=True,
    )


# ── Main ──────────────────────────────────────────────────────────────────────


def _render_session_report(report) -> None:
    """End-of-read engine-health summary panel (CSV mode).

    Physics-severity only, self-baselined on the first 20% of the recording
    (that period is excluded from the verdict), with untested faults marked. This
    is the honest end-of-read verdict; the live severity strip is only a glance.
    """
    v = report.verdict
    if v.startswith("DEVELOPING"):
        vcolor = ACCENT_ALERT
    elif v.startswith("HEALTHY"):
        vcolor = SEVERITY_OK
    else:
        vcolor = TEXT_SECONDARY  # INSUFFICIENT DATA

    st.markdown(
        f'<div style="border:1px solid {BORDER_STRONG};border-radius:10px;'
        f'padding:16px 18px;margin-bottom:14px;background:rgba(255,255,255,0.02);">'
        f'<div style="font-family:{FONT_DISPLAY};font-size:11px;letter-spacing:0.12em;'
        f'text-transform:uppercase;color:{TEXT_SECONDARY};">End-of-Read Health Report</div>'
        f'<div style="font-family:{FONT_MONO};font-size:22px;font-weight:700;'
        f'color:{vcolor};margin-top:6px;">{v}</div>'
        f'<div style="font-family:{FONT_BODY};font-size:11px;color:{TEXT_MUTED};'
        f'margin-top:4px;">{report.n_evaluable_windows} evaluable · '
        f'{report.n_baseline_windows} baseline (excluded) · '
        f'{report.n_untested_windows} untested windows</div></div>',
        unsafe_allow_html=True,
    )

    labels = {
        "air_system": "AIR SYSTEM",
        "fuel_system": "FUEL SYSTEM",
        "coolant_temp_sensor": "COOLANT SENSOR",
        "throttle_position_sensor": "TPS",
    }
    by_fault = {fr.fault: fr for fr in report.faults}
    cols = st.columns(4)
    for fault, col in zip(labels, cols):
        fr = by_fault.get(fault)
        with col:
            if fr is None:
                status_txt, scolor, detail = "—", TEXT_MUTED, ""
            elif fr.status == "untested":
                status_txt, scolor, detail = "UNTESTED", TEXT_MUTED, "PID unavailable"
            elif fr.status == "detected":
                status_txt, scolor = "DETECTED", ACCENT_ALERT
                detail = f"severity {fr.severity_pct:.0f}%"
            elif fr.status == "inconclusive":
                status_txt, scolor = "INCONCLUSIVE", SEVERITY_CAUTION
                detail = f"{fr.window_share_pct:.0f}% label share, ~0 severity"
            else:
                status_txt, scolor, detail = "HEALTHY", SEVERITY_OK, ""
            st.markdown(
                f'<div style="padding:6px 2px;">'
                f'<div style="font-family:{FONT_DISPLAY};font-size:10px;'
                f"text-transform:uppercase;letter-spacing:0.1em;"
                f'color:{TEXT_SECONDARY};">{labels[fault]}</div>'
                f'<div style="font-family:{FONT_MONO};font-size:16px;font-weight:700;'
                f'color:{scolor};margin-top:6px;">{status_txt}</div>'
                f'<div style="font-family:{FONT_BODY};font-size:10px;'
                f'color:{TEXT_MUTED};">{detail}</div></div>',
                unsafe_allow_html=True,
            )

    for c in report.caveats:
        st.markdown(
            f'<div style="font-family:{FONT_BODY};font-size:10px;color:{TEXT_MUTED};'
            f'margin-top:2px;">• {c}</div>',
            unsafe_allow_html=True,
        )


def _render_severity_strip(state: DashboardState) -> None:
    """Compact CURRENT-severity bars — physics severity only, no 60s forecast.

    One slim bar per fault (0-100%), coloured by level. The forecaster (which
    produced phantom 17%/27% severities on healthy cars) is intentionally not
    shown. Untested faults (primary PID unavailable, e.g. air_system on a MAF
    car) show "UNTESTED" instead of a bar. On a healthy engine every bar sits
    near 0 — a simple, honest readout rather than four busy gauges.
    """
    faults = [
        ("air_system", "AIR SYSTEM"),
        ("fuel_system", "FUEL SYSTEM"),
        ("coolant_temp_sensor", "COOLANT SENSOR"),
        ("throttle_position_sensor", "TPS"),
    ]
    untested = set(getattr(state, "untested_faults", []) or [])
    cols = st.columns(4)
    for (fault, label), col in zip(faults, cols):
        with col:
            if fault in untested:
                body = (
                    f'<div style="font-family:{FONT_MONO};font-size:15px;font-weight:700;'
                    f'color:{TEXT_MUTED};margin-top:8px;">UNTESTED</div>'
                    f'<div style="font-family:{FONT_BODY};font-size:9px;'
                    f'color:{TEXT_MUTED};">PID unavailable on this vehicle</div>'
                )
            else:
                sev = float(state.severities.get(fault, 0.0))
                pct = max(0, min(100, int(round(sev * 100))))
                color = severity_color(sev)
                body = (
                    f'<div style="height:8px;border-radius:4px;background:{BORDER};'
                    f'overflow:hidden;margin-top:10px;">'
                    f'<div style="height:100%;width:{pct}%;background:{color};'
                    f'border-radius:4px;"></div></div>'
                    f'<div style="font-family:{FONT_MONO};font-size:22px;font-weight:700;'
                    f'color:{TEXT_PRIMARY};margin-top:4px;line-height:1.1;">{pct}%</div>'
                )
            st.markdown(
                f'<div style="padding:6px 2px;">'
                f'<div style="font-family:{FONT_DISPLAY};font-size:10px;'
                f"text-transform:uppercase;letter-spacing:0.1em;"
                f'color:{TEXT_SECONDARY};">{label}</div>{body}</div>',
                unsafe_allow_html=True,
            )


# Render at most this many frames/sec during CSV replay, regardless of playback
# speed. At high speeds we advance MANY rows per rerun but repaint once, so the
# screen stays readable instead of flashing ~50x/sec.
_TARGET_FPS = 5.0


def _rows_per_tick(speed: float) -> int:
    """Rows to advance per rerun so render cadence stays ~_TARGET_FPS.

    speed <= _TARGET_FPS  -> 1 row/tick (render rate == speed, smooth).
    speed  > _TARGET_FPS  -> speed/_TARGET_FPS rows/tick, one repaint per tick.
    """
    return max(1, round(speed / _TARGET_FPS))


def main() -> None:
    _init_session_state()
    inject_global_styles()

    st.title("Predictive Maintenance — Live OBD-II Dashboard")

    engine = _load_engine()
    speed = _render_sidebar(engine)

    if engine is None:
        st.error(
            "Model files not found. Run `python -m scripts.rebuild_all` first "
            "to train the classifier and forecasters."
        )
        return

    # Warn as soon as any PID is NaN-filled — one missing PID already degrades
    # all cross-PID ratio features (THROTTLE_TO_PEDAL_RATIO, MAP_PER_THROTTLE).
    if engine.degraded_pid_count >= 1:
        st.warning(
            f"WARNING: {engine.degraded_pid_count} PIDs unsupported by this ECU — "
            f"classifier confidence is degraded. Run with a vehicle that supports all 14 PIDs."
        )

    # ── Advance one row (if playing) ──────────────────────────────────────────
    source = (
        st.session_state.streamer
        if st.session_state.source_type == "csv"
        else st.session_state.live_source
    )

    if st.session_state.playing and source is not None:
        st.session_state.session_report = None  # clear stale report while replaying
        is_csv = st.session_state.source_type == "csv"
        # CSV: advance multiple rows per rerun so we can repaint once at
        # ~_TARGET_FPS instead of once per row (the 50x flashing). Live: 1/tick.
        rows_this_tick = _rows_per_tick(speed) if is_csv else 1

        for _step in range(rows_this_tick):
            row = source.next_row()

            if row is None:
                if getattr(source, "exhausted", False):
                    # CSV finished — build the end-of-read health report from the
                    # completed per-window history (self-baseline + untested
                    # handling live inside build_session_report).
                    st.session_state.playing = False
                    if is_csv:
                        from src.eval.session_report import build_session_report

                        # Session-level untested set from the ENGINE — the last
                        # DashboardState can be a between-windows snapshot with
                        # an empty list, which previously let air_system count
                        # as evaluable ("DETECTED, severity 0%").
                        st.session_state.session_report = build_session_report(
                            engine.window_history, engine.session_untested_faults
                        )
                    break
                else:
                    # Live source: no fresh row ready this tick — reschedule quickly
                    time.sleep(0.05)
                    st.rerun()
                    return

            if not is_csv:
                # T3.1: InferenceEngine resamples live rows to 1 Hz before the
                # 60-row buffer, so features use a 1-second axis regardless of
                # adapter poll rate. Warn if the adapter is too slow to resample.
                poll_hz = getattr(source, "measured_poll_hz", 0.0)
                engine.set_sample_hz(1.0)  # resampler guarantees 1-Hz downstream
                if 0 < poll_hz < 0.3:
                    st.error(
                        "Adapter poll rate {:.2f} Hz is below the 0.3 Hz floor — "
                        "hold-last resampling fills the window with near-identical "
                        "rows and std features collapse to zero. "
                        "Use a faster ELM327 adapter.".format(poll_hz)
                    )

            state = engine.update(row)
            st.session_state.latest_state = state
            st.session_state.pid_history.append(row)
            _update_alert_log(state)

    # ── Render current state ──────────────────────────────────────────────────
    state: DashboardState | None = st.session_state.latest_state

    if state is None:
        if st.session_state.source_type == "live":
            st.info("Connect to a vehicle in the sidebar to begin live monitoring.")
        else:
            st.info("Select a session file in the sidebar and press **Play** to begin.")
    else:
        _report = st.session_state.get("session_report")
        if _report is not None:
            _render_session_report(_report)

        _render_status_banner(state)

        _section_header("Fault Severity")
        _render_severity_strip(state)

        _section_header("Live PID Readings")
        _render_pid_strip(st.session_state.pid_history)

        col_log, col_shap = st.columns([1, 1])
        with col_log:
            _section_header("Alert Log")
            _render_alert_log(st.session_state.alert_log)
        with col_shap:
            _section_header("Top SHAP Features")
            _render_shap_panel(state)

        # Workshop diagnostic steps — only shown when a fault is confirmed
        _render_recommendations(state)

        # Elapsed time — custom mono readout (avoids default metric chrome)
        st.sidebar.markdown(
            f'<div style="border-top:1px solid {BORDER};margin-top:12px;padding-top:12px;">'
            f'<div style="font-family:{FONT_DISPLAY};font-size:9px;text-transform:uppercase;'
            f'letter-spacing:0.12em;color:{TEXT_MUTED};">SESSION TIME</div>'
            f'<div style="font-family:{FONT_MONO};font-size:22px;font-weight:700;'
            f'color:{TEXT_PRIMARY};line-height:1.2;">{state.elapsed_s:,} s</div>'
            f"</div>",
            unsafe_allow_html=True,
        )

    # ── Schedule next rerun (auto-advance) ───────────────────────────────────
    if st.session_state.playing:
        if st.session_state.source_type == "csv":
            csv_speed = (
                st.session_state.streamer.speed if st.session_state.streamer else 1.0
            )
            # We advanced _rows_per_tick(csv_speed) rows this rerun; sleep so the
            # effective row rate still equals csv_speed while repaints stay near
            # _TARGET_FPS. Floor at 20 ms to avoid hammering the render loop.
            time.sleep(max(0.02, _rows_per_tick(csv_speed) / csv_speed))
        else:
            # Live mode: poll at ~20 Hz; actual OBD rows arrive at 1 Hz
            time.sleep(0.05)
        st.rerun()


if __name__ == "__main__":
    main()