export const USEFUL_PIDS = [
  'ENGINE_RPM', 'VEHICLE_SPEED', 'THROTTLE', 'ENGINE_LOAD',
  'COOLANT_TEMPERATURE', 'LONG_TERM_FUEL_TRIM_BANK_1',
  'SHORT_TERM_FUEL_TRIM_BANK_1', 'INTAKE_MANIFOLD_PRESSURE',
  'ACCELERATOR_PEDAL_POSITION_D', 'ACCELERATOR_PEDAL_POSITION_E',
  'COMMANDED_THROTTLE_ACTUATOR', 'INTAKE_AIR_TEMPERATURE',
  'TIMING_ADVANCE', 'CONTROL_MODULE_VOLTAGE',
] as const;
